version: "3"

services:
  backend:
    build: ./backend_puppeteer
    container_name: backend
    # use nodemon rather than node for local dev
    command: 
      - /bin/sh
      - -c
      - |
        npm install
        node index.js
    env_file: ./backend_puppeteer/.env
    volumes:
      - ./backend_puppeteer:/usr/src/app
      - ./backend_puppeteer/node_modules:/usr/src/app/node_modules
    links:
      - mysql
    depends_on:
      - mysql

  frontend:
    build: ./frontend_react
    # image: "${WEB_IMAGE}"
    container_name: frontend
    volumes:
      - ./frontend_react:/usr/src/web
      - ./frontend_react/node_modules:/usr/src/web/node_modules
      - ./frontend_react/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:2026
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/data/db

volumes:
  data:
  nodemodules: {}